#ifndef WARBLER_LEXICON_KEYWORD_HPP
#define WARBLER_LEXICON_KEYWORD_HPP

#include <warbler/lexicon/token.hpp>

namespace warbler::lexicon
{
	enum KeywordType
	{
		KEYWORD_NONE,
		KEYWORD_MUT,
		KEYWORD_FUNC,
		KEYWORD_VAR,
		KEYWORD_TYPE,
		KEYWORD_RETURN,
		KEYWORD_FOR,
		KEYWORD_WHILE,
		KEYWORD_LOOP,
		KEYWORD_CONTINUE,
		KEYWORD_BREAK,
		KEYWORD_IF,
		KEYWORD_THEN,
		KEYWORD_ELSE,
		KEYWORD_MATCH,
		KEYWORD_CASE,
		KEYWORD_STRUCT,
		KEYWORD_UNION,
		KEYWORD_ENUM,
		KEYWORD_TRUE,
		KEYWORD_FALSE,
		KEYWORD_IMPORT,
		KEYWORD_EXPORT,
		KEYWORD_PUBLIC,
		KEYWORD_PRIVATE
	};

	KeywordType get_keyword_type(const Token& token);
}

#endif
